get  http://127.0.0.1:5000/organiser/events 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMDQzMTY4NCwianRpIjoiYTgwOTQ5ZTEtOGMyNi00YWQ2LTlhNzAtYWU0YjY4OWU5ODc0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzIwNDMxNjg0LCJjc3JmIjoiZTAyNDA5ZGEtNDU4Ni00YjQ5LTkzYjEtOWZjYTI4ZGUyMmYyIiwiZXhwIjoxNzIwNDMyNTg0fQ.JXjNhfTIgEFhYgJR6YDv1j47iYTZZrqBXMjesyYskiU


# {
# "email":"test@email.com",
# "password":"12345678"
# }