get  http://127.0.0.1:5000/attendee/events 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMDU5NDY1OCwianRpIjoiMjgyYmNmNmMtOTRjZS00ZjIxLWE4MzQtMDdjYTQ4NGVjZDU1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNzIwNTk0NjU4LCJjc3JmIjoiZTliOTY2MDAtMWI3Yy00NjQxLWFlZmEtMDMyOTUyMjVmNjY3IiwiZXhwIjoxNzIwNTk1NTU4fQ.imnjuJt6geubnJ6qNTwR15GD6tsnEOAb1YEi3H_8dKs


# {
# "email":"test@email.com",
# "password":"12345678"
# }