"""Add Ticket_no to Booking

Revision ID: c9f36648f6f0
Revises: 43b8ecb29c85
Create Date: 2024-07-10 10:05:52.111797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f36648f6f0'
down_revision = '43b8ecb29c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_no', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('ticket_no')

    # ### end Alembic commands ###
